#Data Preprocessing


In [3]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd  #manage and select datasets

In [48]:
#import data
url='https://raw.githubusercontent.com/Ashleshk/Machine-Learning-A-Z-hands-on-Python-And-R-in-data-Science/master/Machine%20Learning%20A-Z/Part%201%20-%20Data%20Preprocessing/Data.csv'

dataset = pd.read_csv(url)
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [49]:
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [50]:
from sklearn import preprocessing
  
# label_encoder object knows how to understand word labels.
le_country = preprocessing.LabelEncoder()
# Encode labels in column 'species'.
dataset['Country']= le_country.fit_transform(dataset['Country'])
le_Purchased=preprocessing.LabelEncoder()
dataset['Purchased']=le_Purchased.fit_transform(dataset['Purchased'])


In [51]:
dataset

Country   Age   Salary  Purchased
0        0  44.0  72000.0          0
1        2  27.0  48000.0          1
2        1  30.0  54000.0          0
3        2  38.0  61000.0          0
4        1  40.0      NaN          1
5        0  35.0  58000.0          1
6        2   NaN  52000.0          0
7        0  48.0  79000.0          1
8        1  50.0  83000.0          0
9        0  37.0  67000.0          1

In [52]:
X = dataset.iloc[:, :-1].values  #matrix of feature  : all line , all colums except last one 
y = dataset.iloc[:, 3].values   #depenedetnt variable /output

In [53]:
X

array([[0.0e+00, 4.4e+01, 7.2e+04],
       [2.0e+00, 2.7e+01, 4.8e+04],
       [1.0e+00, 3.0e+01, 5.4e+04],
       [2.0e+00, 3.8e+01, 6.1e+04],
       [1.0e+00, 4.0e+01,     nan],
       [0.0e+00, 3.5e+01, 5.8e+04],
       [2.0e+00,     nan, 5.2e+04],
       [0.0e+00, 4.8e+01, 7.9e+04],
       [1.0e+00, 5.0e+01, 8.3e+04],
       [0.0e+00, 3.7e+01, 6.7e+04]])

In [54]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [55]:
# Taking care of missing data
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer = imputer.fit(X[:,1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
X

array([[0.00000000e+00, 4.40000000e+01, 7.20000000e+04],
       [2.00000000e+00, 2.70000000e+01, 4.80000000e+04],
       [1.00000000e+00, 3.00000000e+01, 5.40000000e+04],
       [2.00000000e+00, 3.80000000e+01, 6.10000000e+04],
       [1.00000000e+00, 4.00000000e+01, 6.37777778e+04],
       [0.00000000e+00, 3.50000000e+01, 5.80000000e+04],
       [2.00000000e+00, 3.87777778e+01, 5.20000000e+04],
       [0.00000000e+00, 4.80000000e+01, 7.90000000e+04],
       [1.00000000e+00, 5.00000000e+01, 8.30000000e+04],
       [0.00000000e+00, 3.70000000e+01, 6.70000000e+04]])

In [56]:
#Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [58]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()

X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

sc_y = StandardScaler()    # not required 
y_train = sc_y.fit_transform(y_train.reshape(-1,1))